version: "3.5"

services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: "turboapp"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
    volumes:
      - db:/var/lib/postgresql/data

    # 初期処理が必要な場合
    # volumes:
    #   - ./db/init:/docker-entrypoint-initdb.d

volumes:
  db: