/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/users": {
    /**
     * User一覧取得
     * @description 登録されているUserをページネーション取得します。
     */
    get: {
      parameters: {
        query: {
          currentPage: components["parameters"]["CurrentPage"];
          email: components["parameters"]["EmailKeyword"];
        };
      };
      responses: {
        200: components["responses"]["GetUsersResponse"];
        404: components["responses"]["NotFoundErrorResponse"];
        500: components["responses"]["InternalServerErrorResponse"];
      };
    };
  };
  "/users/{userId}": {
    /**
     * User取得
     * @description 登録されているユーザーを一覧で取得します。
     */
    get: {
      parameters: {
        path: {
          userId: components["parameters"]["UserId"];
        };
      };
      responses: {
        200: components["responses"]["GetUserResponse"];
        404: components["responses"]["NotFoundErrorResponse"];
        500: components["responses"]["InternalServerErrorResponse"];
      };
    };
  };
  "/users/{userId}/update": {
    /**
     * User更新
     * @description ユーザー情報を更新します。
     */
    post: {
      parameters: {
        path: {
          userId: components["parameters"]["UserId"];
        };
      };
      requestBody: components["requestBodies"]["UpdateUserRequestBody"];
      responses: {
        200: components["responses"]["UpdateUserResponse"];
        404: components["responses"]["NotFoundErrorResponse"];
        500: components["responses"]["InternalServerErrorResponse"];
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Paging: {
      /** 総ページ数 */
      totalPages: number;
      /** 取得したページ */
      currentPage: number;
      /** ページ毎の表示件数 */
      paginate: number;
      /** アイテムの総数 */
      total: number;
    };
    User: {
      /** ID */
      id: string;
      /** ユーザー名 */
      name: string;
      /** メールアドレス */
      email: string;
      /** ユーザー画像URL */
      imageUrl: string;
    };
    Users: components["schemas"]["User"][];
  };
  responses: {
    GetUserResponse: {
      content: {
        "application/json": components["schemas"]["User"];
      };
    };
    UpdateUserResponse: {
      content: {
        "application/json": components["schemas"]["User"];
      };
    };
    GetUsersResponse: {
      content: {
        "application/json": {
          users: components["schemas"]["Users"];
          paging: components["schemas"]["Paging"];
        };
      };
    };
    NotFoundErrorResponse: {
      content: {
        "application/json": {
          /**
           * @description ステータスコード
           * @example 404
           */
          code: number;
          /**
           * @description エラーメッセージ
           * @example Not found resource.
           */
          message?: string;
        };
      };
    };
    InternalServerErrorResponse: {
      content: {
        "application/json": {
          /**
           * @description ステータスコード
           * @example 500
           */
          code: number;
          /**
           * @description エラーメッセージ
           * @example Server error.
           */
          message?: string;
        };
      };
    };
  };
  parameters: {
    /** @description 現在のページ番号（1〜） */
    CurrentPage: number;
    /** @description ページ毎の表示件数 */
    Paginate: number;
    /** @description メールアドレス検索値 */
    EmailKeyword: string;
    /** @description 取得したいユーザーIDを指定します。 */
    UserId: string;
  };
  requestBodies: {
    UpdateUserRequestBody: {
      content: {
        "application/json": {
          /** ユーザー名 */
          name: string;
          /** メールアドレス */
          email: string;
        };
      };
    };
  };
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
